import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'

export async function POST() {
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL

  if (!serviceRoleKey || !supabaseUrl) {
    return NextResponse.json(
      {
        error:
          'Missing Supabase configuration. Make sure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set in your environment variables.',
      },
      { status: 400 }
    )
  }

  const supabaseAdmin = createAdminClient()

  try {
    // Ensure 'attachments' storage bucket exists
    const { data: bucketData, error: bucketError } = await supabaseAdmin.storage.createBucket('attachments', {
      public: true,
      fileSizeLimit: 10485760, // 10MB limit
    })
    
    if (bucketError && !bucketError.message.includes('already exists')) {
      console.warn('Non-fatal error creating storage bucket:', bucketError.message)
    }

    // 1. Fetch all auth users to find existing test accounts and delete them
    const { data: { users }, error: listError } = await supabaseAdmin.auth.admin.listUsers({
      perPage: 1000,
    })

    if (listError) throw listError

    const testEmails = [
      'manager@test.com',
      'employee@test.com',
      'alice@test.com',
      'bob@test.com',
      'charlie@test.com',
      'diana@test.com',
      'ethan@test.com',
    ]

    const usersToDelete = users.filter((u) => u.email && testEmails.includes(u.email))

    for (const u of usersToDelete) {
      const { error: delError } = await supabaseAdmin.auth.admin.deleteUser(u.id)
      if (delError) console.error(`Error deleting user ${u.email}:`, delError)
    }

    // Wait 1 second to ensure trigger deletions cascade in the DB
    await new Promise((resolve) => setTimeout(resolve, 1000))

    // 2. Create the Manager Account
    const { data: mgrUser, error: mgrError } = await supabaseAdmin.auth.admin.createUser({
      email: 'manager@test.com',
      password: 'Password123',
      email_confirm: true,
      user_metadata: {
        full_name: 'Marcus Vance (Manager)',
        role: 'manager',
      },
    })
    if (mgrError) throw mgrError

    // 3. Create the Main Employee Account
    const { data: empUser, error: empError } = await supabaseAdmin.auth.admin.createUser({
      email: 'employee@test.com',
      password: 'Password123',
      email_confirm: true,
      user_metadata: {
        full_name: 'Edward Cole',
        role: 'employee',
      },
    })
    if (empError) throw empError

    // 4. Create 5 additional employees
    const additionalEmployees = [
      { email: 'alice@test.com', name: 'Alice Smith' },
      { email: 'bob@test.com', name: 'Bob Jones' },
      { email: 'charlie@test.com', name: 'Charlie Brown' },
      { email: 'diana@test.com', name: 'Diana Prince' },
      { email: 'ethan@test.com', name: 'Ethan Hunt' },
    ]

    const employeeIds: string[] = [empUser.user!.id]

    for (const emp of additionalEmployees) {
      const { data: userObj, error: err } = await supabaseAdmin.auth.admin.createUser({
        email: emp.email,
        password: 'Password123',
        email_confirm: true,
        user_metadata: {
          full_name: emp.name,
          role: 'employee',
        },
      })
      if (err) {
        console.error(`Error creating employee ${emp.email}:`, err)
      } else if (userObj.user) {
        employeeIds.push(userObj.user.id)
      }
    }

    // Wait 1 second to ensure profiles are generated by database triggers
    await new Promise((resolve) => setTimeout(resolve, 1000))

    // 5. Generate 25 requests mapped to different categories, priorities, statuses
    const requestTemplates = [
      { title: 'Annual Leave Request', category: 'Leave', desc: 'Requesting 5 days off for annual family vacation.' },
      { title: 'New MacBook Pro', category: 'Equipment', desc: 'Requesting memory upgrade for local development; current laptop is stalling.' },
      { title: 'Adobe Creative Cloud Access', category: 'Software Access', desc: 'Need access to Photoshop and Illustrator for asset design.' },
      { title: 'Q3 Marketing Budget Approval', category: 'Budget', desc: 'Approval for Q3 ad spend on social media channels.' },
      { title: 'Travel to Tech Conference', category: 'Travel', desc: 'Attending JSConf next month in San Francisco. Requesting flights and accommodation coverage.' },
      { title: 'Ergonomic Office Chair', category: 'Equipment', desc: 'Need an ergonomic chair to prevent back pain during long hours.' },
      { title: 'GitHub Enterprise Account', category: 'Software Access', desc: 'Need access to organization private repositories.' },
      { title: 'AWS Sandbox Budget', category: 'Budget', desc: 'Requesting $200/month budget for experimental testing of serverless models.' },
      { title: 'Team Building Dinner', category: 'Budget', desc: 'Budget approval for local team dinner; approx 10 team members.' },
      { title: 'Figma Professional License', category: 'Software Access', desc: 'Need professional tier access to design prototype interactions.' },
      { title: 'Sick Leave (Dental)', category: 'Leave', desc: 'Taking 2 days sick leave for dental surgery.' },
      { title: 'Extra 4K Monitor', category: 'Equipment', desc: 'Requesting a second 27" monitor to improve development efficiency.' },
      { title: 'Salesforce CRM Access', category: 'Software Access', desc: 'Need login for sales reporting and pipeline audit.' },
      { title: 'Client Onboarding Travel', category: 'Travel', desc: 'Client onsite meeting in Chicago for setup and training.' },
      { title: 'Home Internet Reimbursement', category: 'Other', desc: 'Monthly home internet reimbursement for remote work policy.' },
      { title: 'IntelliJ IDEA License', category: 'Software Access', desc: 'Developer IDE license for backend Java/TS development.' },
      { title: 'AV Conference System Upgrade', category: 'Budget', desc: 'Requesting budget for new microphones and camera in Meeting Room B.' },
      { title: 'React Advanced Course Reimbursement', category: 'Other', desc: 'Reimbursement for online professional certification.' },
      { title: 'External Hard Drive 2TB', category: 'Equipment', desc: 'Backup drive for local project assets and raw videos.' },
      { title: 'QBR Dublin Travel', category: 'Travel', desc: 'Quarterly planning meeting at Dublin headquarters.' },
      { title: 'MATLAB License Key', category: 'Software Access', desc: 'Need MATLAB access for data modeling scripts.' },
      { title: 'Office Keycard Replacement', category: 'Other', desc: 'Lost building keycard; requesting a replacement card.' },
      { title: 'Product Launch Catering', category: 'Budget', desc: 'Food and drinks budget for launching the new product version.' },
      { title: 'Emergency Sick Leave', category: 'Leave', desc: 'Out of office due to flu.' },
      { title: 'GitHub Copilot Subscription', category: 'Software Access', desc: 'AI assistant license to speed up coding tasks.' },
    ]

    const priorities = ['Low', 'Medium', 'High']
    const statuses = ['Pending', 'Approved', 'Rejected']

    const requestsToInsert = []

    for (let i = 0; i < requestTemplates.length; i++) {
      const template = requestTemplates[i]
      // Rotate employee IDs
      const employeeId = employeeIds[i % employeeIds.length]
      
      // Rotate priorities
      const priority = priorities[i % priorities.length]

      // Set status ratios:
      // i % 3 = 0 -> Pending
      // i % 3 = 1 -> Approved
      // i % 3 = 2 -> Rejected
      const status = statuses[i % statuses.length]

      // Manager comments
      let managerComment = null
      if (status === 'Approved') {
        managerComment = 'Approved. Please coordinate with the finance team to process.'
      } else if (status === 'Rejected') {
        managerComment = 'Rejected. Budget limits reached for this quarter, or dates conflict with major team releases.'
      }

      // Random dates in the future
      const start = new Date()
      start.setDate(start.getDate() + (i + 1) * 3)
      const end = new Date(start)
      end.setDate(end.getDate() + 4)

      requestsToInsert.push({
        employee_id: employeeId,
        title: template.title,
        description: template.desc,
        category: template.category,
        priority: priority,
        start_date: start.toISOString().split('T')[0],
        end_date: end.toISOString().split('T')[0],
        status: status,
        manager_comment: managerComment,
        created_at: new Date(Date.now() - (25 - i) * 60 * 60 * 1000).toISOString(), // staggered creation times
        updated_at: new Date().toISOString(),
      })
    }

    const { error: insertError } = await supabaseAdmin.from('requests').insert(requestsToInsert)
    if (insertError) throw insertError

    return NextResponse.json({
      success: true,
      message: 'Demo accounts and 25 requests successfully seeded!',
      accounts: {
        manager: { email: 'manager@test.com', password: 'Password123' },
        employee: { email: 'employee@test.com', password: 'Password123' },
        additional: additionalEmployees.map((e) => e.email),
      },
    })
  } catch (error: any) {
    console.error('Seeding Error:', error)
    return NextResponse.json(
      { error: error.message || 'An error occurred during database seeding.' },
      { status: 500 }
    )
  }
}

export async function GET() {
  // Allow GET requests too, for simple seeding via browser or button triggers
  return await POST()
}
